[general]
import = [ "~/.config/alacritty/tokyonight_night.toml" ]

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "Mononoki Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Mononoki Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font Mono"
# style = "Regular"
style = "Italic"

[window]
opacity = 0.90
blur = true
# for macos
option_as_alt = "Both"

[[hints.enabled]]
command         = "xdg-open" # On Linux/BSD
# command       = "open" # On macOS
# command       = { program = "cmd", args = [ "/c", "start",  "" ] } # On Windows
hyperlinks      = true
post_processing = true
persist         = false
mouse.enabled   = true
mouse.mods      = "Control" # "Control|Shift" is my preference
binding         = { key = "O", mods = "Control|Shift" }
regex           = "(ipfs:|ipns:|magnet:|mailto:|gemini://|go‐pher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

# for macos
[[keyboard.bindings]]
key = "A"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
key = "B"
mods = "Command"
chars = "\u0002"

[[keyboard.bindings]]
key = "C"
mods = "Command"
chars = "\u0003"

[[keyboard.bindings]]
key = "D"
mods = "Command"
chars = "\u0004"

[[keyboard.bindings]]
key = "E"
mods = "Command"
chars = "\u0005"

[[keyboard.bindings]]
key = "F"
mods = "Command"
chars = "\u0006"

[[keyboard.bindings]]
key = "G"
mods = "Command"
chars = "\u0007"

[[keyboard.bindings]]
key = "H"
mods = "Command"
chars = "\u0008"

[[keyboard.bindings]]
key = "I"
mods = "Command"
chars = "\u0009"

[[keyboard.bindings]]
key = "J"
mods = "Command"
chars = "\u000A"

[[keyboard.bindings]]
key = "K"
mods = "Command"
chars = "\u000B"

[[keyboard.bindings]]
key = "L"
mods = "Command"
chars = "\u000C"

[[keyboard.bindings]]
key = "M"
mods = "Command"
chars = "\u000D"

[[keyboard.bindings]]
key = "N"
mods = "Command"
chars = "\u000E"

[[keyboard.bindings]]
key = "O"
mods = "Command"
chars = "\u000F"

[[keyboard.bindings]]
key = "P"
mods = "Command"
chars = "\u0010"

[[keyboard.bindings]]
key = "Q"
mods = "Command"
chars = "\u0011"

[[keyboard.bindings]]
key = "R"
mods = "Command"
chars = "\u0012"

[[keyboard.bindings]]
key = "S"
mods = "Command"
chars = "\u0013"

[[keyboard.bindings]]
key = "T"
mods = "Command"
chars = "\u0014"

[[keyboard.bindings]]
key = "U"
mods = "Command"
chars = "\u0015"

[[keyboard.bindings]]
key = "V"
mods = "Command"
chars = "\u0016"

[[keyboard.bindings]]
key = "W"
mods = "Command"
chars = "\u0017"

[[keyboard.bindings]]
key = "X"
mods = "Command"
chars = "\u0018"

[[keyboard.bindings]]
key = "Y"
mods = "Command"
chars = "\u0019"

[[keyboard.bindings]]
key = "Z"
mods = "Command"
chars = "\u001A"

[[keyboard.bindings]]
key = "LBracket"
mods = "Command"
chars = "\u001B"

[[keyboard.bindings]]
key = "Backslash"
mods = "Command"
chars = "\u001C"

[[keyboard.bindings]]
key = "RBracket"
mods = "Command"
chars = "\u001D"

[[keyboard.bindings]]
key = "Key6"
mods = "Command|Shift"
chars = "\u001E"

[[keyboard.bindings]]
key = "Minus"
mods = "Command|Shift"
chars = "\u001F"

[[keyboard.bindings]]
key = "Key2"
mods = "Command|Shift"
chars = "\u0000"
